# Generated by Django 5.2.7 on 2025-10-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('available', models.BooleanField(default=True)),
                ('pages', models.IntegerField()),
                ('rental_price', models.FloatField(max_length=10)),
                ('buy_price', models.FloatField(max_length=10)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
