# Generated by Django 5.2.7 on 2025-10-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_project', '0002_address_book_category_favorite_infouser_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infouser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrador da Página'), ('common user', 'Usuário Comum')], default='common user', max_length=50),
        ),
    ]
