# Generated by Django 5.2.7 on 2025-10-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_project', '0004_alter_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infouser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrador da Página'), ('common user', 'Usuário Comum')], default='common_user', max_length=50),
        ),
    ]
