# Generated by Django 5.2.7 on 2025-10-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_project', '0007_alter_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
