# Generated by Django 5.2.7 on 2025-11-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_project', '0008_alter_book_buy_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_price',
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books/photos/'),
        ),
    ]
